<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"> 
    <!-- boostrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="www/css/cocktails.css">
    <title>Document</title>
</head>
<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <h1>Mister Cocktail</h1>
    </nav>

    <main>
        <form action="#" method="POST" enctype="multipart/form-data">
            <div class="row">
                <div class="col-12">
                    <label for="nom" class="form-label">Nom</label>
                    <input type="text" class="form-control" id="nom" name="nom" placeholder="nom du cocktail">
                    <?php echo $errorName?>
                </div>
                <div class="col-12">
                    <label for="description" class="form-label">Description</label>
                    <textarea name="description" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
                <div class="col-12">
                    <label for="urlPhoto" class="form-label">Photo</label>
                    <input type="file" class="form-control" id="urlPhoto" name="urlPhoto" accept="image/png, image/jpeg">
                    <?php echo $errorFile?>
                </div>
                <div class="col-12">
                    <label for="dateConception" class="form-label">Date de conception</label>
                    <input type="date" class="form-control" id="dateConception" value="2000" name="dateConception">
                </div>
                <div class="col-12">
                    <label for="prixMoyen" class="form-label">Prix</label>
                    <input type="number" class="form-control" id="prixMoyen" value="10" name="prixMoyen">
                </div>
                <div class="col-12">
                    <label for="famille" class="form-label">Famille</label>
                    <select class="form-control" name="idFamille">
                        <?php foreach ($allFamilies as $oneFamily){ ?> 
                        <option value="<?php echo $oneFamily['id']?>"><?php echo $oneFamily['nomFamille']?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-12">
                    <fieldset>
                       <legend>Selecctionez les Ingrédients</legend>
                       <?php foreach($allIngredients as $oneIngredient) {?>
                        <div>
                            <input type="checkbox" id="<?php echo $oneIngredient['nom']?>" name="ingredients[]" value="<?php echo $oneIngredient['id']?>">
                            <label for=""<?php echo $oneIngredient['nom']?>"><?php echo $oneIngredient['nom']?></label>
                            
                        
                        </div>
                       <?php }?>

                    </fieldset>        

                </div>
                <div class="col-12">
                    <input type="submit" value="Ajouter" class="btn btn-primary">
                </div>
            </div>
        </form>
    </main>
</body>
</html>