<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manipulation de la session</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
</head>
<body>
    
    <header class="mb-5 p-5 bg-primary text-white rounded">
        <div class="container">
        <h1>Démonstration du fonctionnement de la session (<a href="readme.php" target="_blank" class="link-warning">lire l'énoncé</a>)</h1>
        <hr>
        <p>Utilisez le formulaire ci-dessous pour vous familiariser avec la manipulation de la session.</p>
        </div>
    </header>

    <section id="session-form">
        <div class="container">
            <div class="row">

                <div class="col-7">
                    <h2>Manipulation de la session</h2> 
                    <p>Utilisez le formulaire ci-dessous pour ajouter ou modifier des variables de la session.</p>

                    <form action="index.php" method="post">
                        <div class="row mb-3">
                            <label for="varName" class="col-4 col-form-label text-end">Nom de la variable</label>
                            <div class="col-8">
                                <input type="text" class="form-control"  name="varName" id="varName" >
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="varValue" class="col-4 col-form-label text-end">Valeur de la variable</label>
                            <div class="col-8">
                                <input type="text" class="form-control"  name="varValue" id="varValue">
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col text-end">
                                <input type="submit" class="btn btn-primary" value="Ajouter/Modifier">
                            </div>
                        </div>
                    </form>
                    <p></p>
                </div>

                <div class="col-5">
                    <?php if (isset($_SESSION)) : ?>
                        <h5>Contenu de la session</h5>   

                        <?php if(isset($message) && $message != '') : ?>
                        <div class="alert alert-success" role="alert">
                            <?=$message?>
                        </div>
                        <?php endif; ?>     

                        <table class="table table-sm">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Nom</th>
                                    <th>Valeur</th>
                                    <th></th>
                                </tr>  
                            </thead>                      
                            <?php foreach ($_SESSION as $name => $value) : ?>
                                <tr>
                                    <td><?=$name?></td>
                                    <td><?=$value?></td>
                                    <td class="text-end">
                                        <a href="index.php?action=remove&varName=<?=$name?>" class="btn btn-danger btn-sm"  data-bs-toggle="tooltip" data-bs-placement="right" title="Supprimer la variable &quot;<?=$name?>&quot;"><i class="fa-solid fa-trash"></i></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table> 
                    <?php else : ?>
                        <div class="alert alert-danger" role="alert">
                            <h5>Votre session n'existe pas !</h5>       
                            <hr>
                            <p>Commencez déjà par la créer avec <em>"session_start()"</em>.</p>
                        </div>
                    <?php endif; ?>
                    <div class="d-grid ">
                        <a href="?action=destroy" class="btn btn-danger" onClick="return confirm('Attention !\nÊtes-vous sûr(e) de vouloir supprimer toutes les données de la session ?');"><i class="fa-solid fa-ban"></i> Vider la session</a>
                    </div>
                </div>
                
   
            </div>
        </div>
    </section> 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/ffe3aa3664.js" crossorigin="anonymous"></script>
</body>
</html>