<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bons de commande (classicmodels)</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/orders.css" rel="stylesheet">
</head>
<body class="container-fluid">
    <header class="jumbotron">
        <h1>Bon de commande n°<?= $_GET['orderNumber'] ?></h1>
        <hr>
        <p><< <a href="index.php">Retour à la page principale</a></p>
    </header>

    <section>
        <!-- Les coordonnées du client -->
    </section>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Produit</th>
                <th>Quantité</th>
                <th class="text-right">Prix Unitaire</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th class="text-right" colspan="3">Montant HT</th>
                <th class="text-right"> $</th>
            </tr>
            <tr>
                <th class="text-right" colspan="3">TVA (20 %)</th>
                <th class="text-right"> $</th>
            </tr>
            <tr>
                <th class="text-right" colspan="3">Montant TTC</th>
                <th class="text-right"> $</th>
            </tr>
        </tfoot>
        <tbody>
        </tbody>
    </table>
</body>
</html>